/**
 * Shared production env loader / first-boot bootstrap for Node / Parspack / cPanel.
 *
 * - Loads .env, .env.production, .env.local, data/production.env (no override of existing process.env)
 * - If production secrets are still missing/weak, writes strong values to data/production.env
 *   so the next Start succeeds without panel gymnastics.
 *
 * Used by server.cjs and (via createRequire) src/server/env.ts.
 */

const fs = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");

function rootDir() {
  return process.cwd();
}

function envFiles() {
  const ROOT = rootDir();
  return [
    path.join(ROOT, ".env"),
    path.join(ROOT, ".env.production"),
    path.join(ROOT, ".env.local"),
    path.join(ROOT, "data", "production.env"),
  ];
}

function isWeakAuthSecret(secret) {
  const normalized = String(secret || "")
    .trim()
    .toLowerCase();
  return (
    !secret ||
    String(secret).trim().length < 32 ||
    normalized.startsWith("change-me") ||
    normalized.includes("replace-with") ||
    normalized === "dev-only-change-me-derakhshan-agency-secret-key-32b" ||
    normalized.includes("showcase-jwt-fallback")
  );
}

function parseEnvFile(contents) {
  /** @type {Record<string, string>} */
  const out = {};
  for (const rawLine of String(contents).split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq <= 0) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    if (key) out[key] = value;
  }
  return out;
}

function applyEnvMap(map, { override = false } = {}) {
  for (const [key, value] of Object.entries(map)) {
    if (!override && process.env[key] != null && String(process.env[key]).length > 0) {
      continue;
    }
    process.env[key] = value;
  }
}

function loadEnvFiles() {
  for (const filePath of envFiles()) {
    try {
      if (!fs.existsSync(filePath)) continue;
      const parsed = parseEnvFile(fs.readFileSync(filePath, "utf8"));
      applyEnvMap(parsed, { override: false });
    } catch (error) {
      console.warn(
        `[production-env] Could not read ${filePath}:`,
        error && error.message ? error.message : error,
      );
    }
  }
}

function productionSecretsStatus() {
  const authSecret = (process.env.AUTH_SECRET || process.env.NEXTAUTH_SECRET || "").trim();
  const seed = (process.env.SEED_ADMIN_PASSWORD || "").trim();
  return {
    authSecret,
    seed,
    authOk: Boolean(authSecret) && !isWeakAuthSecret(authSecret),
    seedOk: seed.length >= 8,
  };
}

function writeProductionEnvFile(authSecret, seedPassword) {
  const dataDir = path.join(rootDir(), "data");
  fs.mkdirSync(dataDir, { recursive: true });
  const filePath = path.join(dataDir, "production.env");
  const body = [
    "# Auto-generated by scripts/production-env.cjs on first production boot.",
    "# Panel Environment Variables override these values when set.",
    "# Keep this file private. Do not commit it.",
    `AUTH_SECRET=${authSecret}`,
    `SEED_ADMIN_PASSWORD=${seedPassword}`,
    "",
  ].join("\n");
  fs.writeFileSync(filePath, body, { encoding: "utf8", mode: 0o600 });
  try {
    fs.chmodSync(filePath, 0o600);
  } catch {
    // best-effort on hosts that ignore chmod
  }
  return filePath;
}

function autoBootstrapProductionSecrets() {
  const status = productionSecretsStatus();
  if (status.authOk && status.seedOk) return { bootstrapped: false, ...status };

  const authSecret = status.authOk
    ? status.authSecret
    : crypto.randomBytes(48).toString("hex");
  const seedPassword = status.seedOk
    ? status.seed
    : crypto.randomBytes(9).toString("base64url");

  let filePath = "";
  try {
    filePath = writeProductionEnvFile(authSecret, seedPassword);
  } catch (error) {
    console.warn(
      "[production-env] Could not write data/production.env; continuing in-memory:",
      error && error.message ? error.message : error,
    );
  }

  process.env.AUTH_SECRET = authSecret;
  process.env.SEED_ADMIN_PASSWORD = seedPassword;

  console.warn("[production-env] =====================================================");
  console.warn("[production-env] Missing production secrets — auto-created once:");
  if (filePath) console.warn(`[production-env]   file: ${filePath}`);
  console.warn(`[production-env]   AUTH_SECRET: (generated, ${authSecret.length} chars)`);
  console.warn(`[production-env]   SEED_ADMIN_PASSWORD: ${seedPassword}`);
  console.warn("[production-env] ورود ادمین: admin@vorqen.ir با همین SEED_ADMIN_PASSWORD");
  console.warn("[production-env] این رمز را ذخیره کنید؛ بعداً از پنل عوضش کنید.");
  console.warn("[production-env] =====================================================");

  return {
    bootstrapped: true,
    filePath,
    authSecret,
    seed: seedPassword,
    authOk: true,
    seedOk: true,
  };
}

function formatRefuseMessage(errors) {
  return [
    "[env] Refusing production start — missing/invalid environment:",
    ...errors.map((e) => `- ${e}`),
    "",
    "رفع فوری در پنل Parspack / cPanel → Environment Variables:",
    "  AUTH_SECRET=<رشته تصادفی حداقل ۳۲ کاراکتر>",
    "  SEED_ADMIN_PASSWORD=<رمز ادمین حداقل ۸ کاراکتر>",
    "سپس Stop → Start.",
    "یا یک‌بار در Application root: node scripts/bootstrap-production-env.cjs",
    "تولید نمونه: node -e \"console.log(require('crypto').randomBytes(48).toString('hex'))\"",
  ].join("\n");
}

/**
 * @param {{ autoBootstrap?: boolean }} [opts]
 */
function ensureProductionEnv(opts = {}) {
  const autoBootstrap = opts.autoBootstrap !== false;

  loadEnvFiles();

  if (process.env.NODE_ENV !== "production") {
    return { skipped: true, reason: "not-production" };
  }

  let bootstrapped = false;
  let status = productionSecretsStatus();
  if ((!status.authOk || !status.seedOk) && autoBootstrap) {
    try {
      const result = autoBootstrapProductionSecrets();
      bootstrapped = Boolean(result.bootstrapped);
      status = productionSecretsStatus();
    } catch (error) {
      console.error(
        "[production-env] Auto-bootstrap failed:",
        error && error.message ? error.message : error,
      );
    }
  }

  const errors = [];
  if (!status.authOk) {
    errors.push(
      "AUTH_SECRET must be a strong random value (min 32 characters). Do not use change-me / replace-with placeholders.",
    );
  }
  if (!status.seedOk) {
    errors.push(
      "SEED_ADMIN_PASSWORD must be set (min 8 characters) for production bootstrap and staff recovery.",
    );
  }

  if (errors.length > 0) {
    const message = formatRefuseMessage(errors);
    const err = new Error(message);
    err.name = "ProductionEnvError";
    throw err;
  }

  return { ok: true, bootstrapped, status };
}

function bootstrapOnly() {
  loadEnvFiles();
  process.env.NODE_ENV = process.env.NODE_ENV || "production";
  const result = autoBootstrapProductionSecrets();
  console.log("[bootstrap-production-env] Done.");
  if (result.filePath) {
    console.log(`[bootstrap-production-env] Wrote ${result.filePath}`);
  }
  console.log(
    `[bootstrap-production-env] SEED_ADMIN_PASSWORD=${process.env.SEED_ADMIN_PASSWORD}`,
  );
  return result;
}

module.exports = {
  loadEnvFiles,
  ensureProductionEnv,
  bootstrapOnly,
  isWeakAuthSecret,
  productionSecretsStatus,
};
